"use client";

import { useState } from "react";
import Link from "next/link";
import { PageHeader } from "@/components/layout/PageHeader";
import { ScheduleBlockCard } from "@/components/schedule/ScheduleBlockCard";
import { WorkloadForecast } from "@/components/schedule/WorkloadForecast";
import { WorkloadStatusBadge } from "@/components/schedule/WorkloadStatusBadge";
import { WeeklyPlanHealth } from "@/components/schedule/WeeklyPlanHealth";
import { buildDayHealth, summarizeWeek } from "@/lib/decision-support";
import { Button } from "@/components/ui/Button";
import { EmptyState } from "@/components/ui/EmptyState";
import { useAppData } from "@/lib/data/store";
import { useSchedule } from "@/lib/data/useSchedule";
import { blockCardKind, formatTimeRange } from "@/lib/schedule-format";
import { currentWeekRange, todayDateOnly } from "@/lib/now";
import type { ScheduleFeedback } from "@/types/models";

const CHECK_IN_LOOKBACK_DAYS = 14;

const DAY_LABELS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

/** Pure day-count between two "YYYY-MM-DD" values — no wall-clock read, unlike `Date.now()`. */
function daysBetweenDateOnly(a: string, b: string): number {
  const toUtcMs = (dateOnly: string) => {
    const [y, m, d] = dateOnly.split("-").map(Number);
    return Date.UTC(y, m - 1, d);
  };
  return Math.round((toUtcMs(b) - toUtcMs(a)) / 86_400_000);
}

function addDays(dateOnly: string, days: number): string {
  const [y, m, d] = dateOnly.split("-").map(Number);
  const date = new Date(y, m - 1, d + days);
  return `${date.getFullYear()}-${(date.getMonth() + 1).toString().padStart(2, "0")}-${date.getDate().toString().padStart(2, "0")}`;
}

export default function SchedulePage() {
  const { start, end } = currentWeekRange();
  const today = todayDateOnly();
  const result = useSchedule(start, end);
  const { submitFeedback, feedback, hydrated, workItems, commitments } = useAppData();

  const days = Array.from({ length: 7 }, (_, i) => addDays(start, i)).map((date) => {
    const [y, m, d] = date.split("-").map(Number);
    return {
      date,
      label: DAY_LABELS[new Date(y, m - 1, d).getDay()],
      // Skipped blocks are historical "this didn't happen" records, not part of the current plan —
      // once something is skipped (and possibly replanned elsewhere), showing its stale ghost
      // alongside a fresh replacement in the same slot is just confusing. Same filter as Today.
      blocks: result.blocks.filter((b) => b.start.slice(0, 10) === date && b.status !== "skipped"),
    };
  });

  // Both derived purely from this same `result` — the week explanation can never disagree with
  // the day-by-day figures beside it (Phase 4.5B, Part 9/10).
  const dayHealth = buildDayHealth(result);
  const weekSummary = summarizeWeek(result);

  const alreadyGaveFeedback = feedback.some((f) => f.dateRange.start === start && f.dateRange.end === end);

  // Ask the fuller set of check-in questions only occasionally (Phase 3A, Part 9) — not every
  // single week — so students aren't stuck re-answering a long questionnaire each time.
  const mostRecentExpandedAnswer = [...feedback]
    .filter((f) => f.breaksFeeling != null)
    .sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1))[0];
  const showExpandedCheckIn =
    !mostRecentExpandedAnswer || daysBetweenDateOnly(mostRecentExpandedAnswer.createdAt.slice(0, 10), today) > CHECK_IN_LOOKBACK_DAYS;

  const [pendingWorkload, setPendingWorkload] = useState<ScheduleFeedback["workloadFeeling"] | null>(null);
  const [breaksFeeling, setBreaksFeeling] = useState<ScheduleFeedback["breaksFeeling"]>();
  const [freeTimeFeeling, setFreeTimeFeeling] = useState<ScheduleFeedback["freeTimeFeeling"]>();
  const [timingFeeling, setTimingFeeling] = useState<ScheduleFeedback["timingFeeling"]>();

  function chooseWorkload(workloadFeeling: ScheduleFeedback["workloadFeeling"]) {
    if (!showExpandedCheckIn) {
      submitFeedback({ dateRange: { start, end }, workloadFeeling });
      return;
    }
    setPendingWorkload(workloadFeeling);
  }

  function finishCheckIn() {
    if (!pendingWorkload) return;
    submitFeedback({ dateRange: { start, end }, workloadFeeling: pendingWorkload, breaksFeeling, freeTimeFeeling, timingFeeling });
    setPendingWorkload(null);
  }

  // The week's day-of-month labels are read from the real clock, which only the client can know
  // for certain to match the server's build-time render — see AppDataProvider for why this must
  // wait for the post-mount hydration flag rather than rendering real dates immediately.
  if (!hydrated) {
    return (
      <div>
        <PageHeader
          title="Schedule"
          description="This week's plan, generated by the scheduling engine from your assignments, tests, and commitments."
        />
        <EmptyState title="Loading your schedule…" />
      </div>
    );
  }

  if (workItems.length === 0 && commitments.length === 0) {
    return (
      <div>
        <PageHeader
          title="Schedule"
          description="This week's plan, generated by the scheduling engine from your assignments, tests, and commitments."
        />
        <EmptyState
          title="Your week hasn't been planned yet"
          description="Add some assignments or tests and StudyFlow will generate your first schedule."
          action={<Link href="/assignments"><Button>Add an assignment</Button></Link>}
        />
      </div>
    );
  }

  return (
    <div>
      <PageHeader
        title="Schedule"
        description="This week's plan, generated by the scheduling engine from your assignments, tests, and commitments."
      />

      <div className="mb-4">
        <WorkloadStatusBadge status={result.workloadStatus} />
      </div>

      <section className="mb-6 rounded-lg border border-border bg-surface p-5">
        <h2 className="mb-3 text-sm font-semibold text-ink">Workload forecast</h2>
        <WorkloadForecast forecast={result.dailyForecast} today={today} />
      </section>

      <section className="mb-6 rounded-lg border border-border bg-surface p-5">
        <h2 className="mb-3 text-sm font-semibold text-ink">How your week looks</h2>
        <WeeklyPlanHealth days={dayHealth} summary={weekSummary} today={today} />
      </section>

      {result.warnings.map((w) => (
        <div key={w.kind} className="mb-4 rounded-md border border-warning-soft bg-warning-soft px-4 py-3 text-sm text-warning">
          {w.message}
        </div>
      ))}
      {result.caughtUp && result.workAheadSuggestions.length > 0 && (
        <div className="mb-4 rounded-md border border-success-soft bg-success-soft px-4 py-3 text-sm text-success">
          <p className="font-medium">You&apos;re caught up this week.</p>
          {result.workAheadSuggestions.map((s) => (
            <p key={s.workItemId} className="mt-1">{s.reason}</p>
          ))}
        </div>
      )}
      {result.feedbackAdjustment !== 1 && (
        <p className="mb-4 text-xs text-ink-faint">
          {result.feedbackAdjustment < 1
            ? "Based on your recent feedback, this schedule is planned slightly lighter than usual."
            : "Based on your recent feedback, this schedule is planned slightly more ambitious than usual."}
        </p>
      )}

      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">
        {days.map((d) => (
          <div key={d.date} className="flex flex-col gap-2">
            <span className={`text-xs font-semibold uppercase tracking-wide ${d.date === today ? "text-brand" : "text-ink-muted"}`}>
              {d.label} {d.date.slice(8, 10)}
            </span>
            <div className="flex flex-col gap-2">
              {d.blocks.length === 0 ? (
                <div className="rounded-md border border-dashed border-border-strong px-3 py-4 text-center text-xs text-ink-faint">
                  Nothing planned
                </div>
              ) : (
                d.blocks.map((block) => (
                  <ScheduleBlockCard
                    key={block.id}
                    title={block.title}
                    timeLabel={formatTimeRange(block)}
                    kind={blockCardKind(block)}
                    status={block.status}
                  />
                ))
              )}
            </div>
          </div>
        ))}
      </div>

      <section className="mt-6 rounded-lg border border-border bg-surface p-5">
        <h2 className="mb-3 text-sm font-semibold text-ink">How does this schedule feel?</h2>
        {alreadyGaveFeedback ? (
          <p className="text-sm text-ink-muted">Thanks — feedback recorded for this week.</p>
        ) : pendingWorkload === null ? (
          <div className="flex gap-2">
            <Button variant="secondary" size="sm" onClick={() => chooseWorkload("too-light")}>
              Too light
            </Button>
            <Button variant="secondary" size="sm" onClick={() => chooseWorkload("just-right")}>
              Just right
            </Button>
            <Button variant="secondary" size="sm" onClick={() => chooseWorkload("too-heavy")}>
              Too heavy
            </Button>
          </div>
        ) : (
          <div className="flex flex-col gap-4">
            <FeelingQuestion
              label="How do the breaks feel?"
              options={[
                { value: "too-few", label: "Too few" },
                { value: "just-right", label: "Good" },
                { value: "too-many", label: "Too many" },
              ]}
              value={breaksFeeling}
              onChange={(v) => setBreaksFeeling(v as ScheduleFeedback["breaksFeeling"])}
            />
            <FeelingQuestion
              label="How much free time would you like?"
              options={[
                { value: "more", label: "More" },
                { value: "about-right", label: "About right" },
                { value: "less", label: "I can handle less" },
              ]}
              value={freeTimeFeeling}
              onChange={(v) => setFreeTimeFeeling(v as ScheduleFeedback["freeTimeFeeling"])}
            />
            <FeelingQuestion
              label="How does the timing feel?"
              options={[
                { value: "earlier", label: "I'd rather start earlier" },
                { value: "about-right", label: "About right" },
                { value: "later", label: "I'd rather work later" },
              ]}
              value={timingFeeling}
              onChange={(v) => setTimingFeeling(v as ScheduleFeedback["timingFeeling"])}
            />
            <div className="flex gap-2">
              <Button size="sm" onClick={finishCheckIn}>Submit</Button>
            </div>
          </div>
        )}
      </section>
    </div>
  );
}

function FeelingQuestion({
  label,
  options,
  value,
  onChange,
}: {
  label: string;
  options: { value: string; label: string }[];
  value?: string;
  onChange: (value: string) => void;
}) {
  return (
    <div>
      <p className="mb-2 text-xs font-medium text-ink-muted">{label}</p>
      <div className="flex flex-wrap gap-2">
        {options.map((opt) => (
          <Button
            key={opt.value}
            size="sm"
            variant={value === opt.value ? "primary" : "secondary"}
            onClick={() => onChange(opt.value)}
          >
            {opt.label}
          </Button>
        ))}
      </div>
    </div>
  );
}
