"use client";

import { PageHeader } from "@/components/layout/PageHeader";
import { ScheduleBlockCard } from "@/components/schedule/ScheduleBlockCard";
import { Button } from "@/components/ui/Button";
import { useAppData } from "@/lib/data/store";
import { useSchedule } from "@/lib/data/useSchedule";
import { blockCardKind, formatTimeRange } from "@/lib/schedule-format";
import { currentWeekRange, todayDateOnly } from "@/lib/now";
import type { ScheduleFeedback } from "@/types/models";

const DAY_LABELS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

function addDays(dateOnly: string, days: number): string {
  const [y, m, d] = dateOnly.split("-").map(Number);
  const date = new Date(y, m - 1, d + days);
  return `${date.getFullYear()}-${(date.getMonth() + 1).toString().padStart(2, "0")}-${date.getDate().toString().padStart(2, "0")}`;
}

export default function SchedulePage() {
  const { start, end } = currentWeekRange();
  const today = todayDateOnly();
  const result = useSchedule(start, end);
  const { submitFeedback, feedback } = useAppData();

  const days = Array.from({ length: 7 }, (_, i) => addDays(start, i)).map((date) => {
    const [y, m, d] = date.split("-").map(Number);
    return { date, label: DAY_LABELS[new Date(y, m - 1, d).getDay()], blocks: result.blocks.filter((b) => b.start.slice(0, 10) === date) };
  });

  const alreadyGaveFeedback = feedback.some((f) => f.dateRange.start === start && f.dateRange.end === end);

  function submit(workloadFeeling: ScheduleFeedback["workloadFeeling"]) {
    submitFeedback({ dateRange: { start, end }, workloadFeeling });
  }

  return (
    <div>
      <PageHeader
        title="Schedule"
        description="This week's plan, generated by the scheduling engine from your assignments, tests, and commitments."
      />

      {result.warnings.map((w) => (
        <div key={w.kind} className="mb-4 rounded-md border border-warning-soft bg-warning-soft px-4 py-3 text-sm text-warning">
          {w.message}
        </div>
      ))}
      {result.caughtUp && result.workAheadSuggestions.length > 0 && (
        <div className="mb-4 rounded-md border border-success-soft bg-success-soft px-4 py-3 text-sm text-success">
          <p className="font-medium">You&apos;re caught up this week.</p>
          {result.workAheadSuggestions.map((s) => (
            <p key={s.workItemId} className="mt-1">{s.reason}</p>
          ))}
        </div>
      )}

      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">
        {days.map((d) => (
          <div key={d.date} className="flex flex-col gap-2">
            <span className={`text-xs font-semibold uppercase tracking-wide ${d.date === today ? "text-brand" : "text-ink-muted"}`}>
              {d.label} {d.date.slice(8, 10)}
            </span>
            <div className="flex flex-col gap-2">
              {d.blocks.length === 0 ? (
                <div className="rounded-md border border-dashed border-border-strong px-3 py-4 text-center text-xs text-ink-faint">
                  Nothing planned
                </div>
              ) : (
                d.blocks.map((block) => (
                  <ScheduleBlockCard
                    key={block.id}
                    title={block.title}
                    timeLabel={formatTimeRange(block)}
                    kind={blockCardKind(block)}
                    status={block.status}
                  />
                ))
              )}
            </div>
          </div>
        ))}
      </div>

      <section className="mt-6 rounded-lg border border-border bg-surface p-5">
        <h2 className="mb-3 text-sm font-semibold text-ink">How does this schedule feel?</h2>
        {alreadyGaveFeedback ? (
          <p className="text-sm text-ink-muted">Thanks — feedback recorded for this week.</p>
        ) : (
          <div className="flex gap-2">
            <Button variant="secondary" size="sm" onClick={() => submit("too-light")}>
              Too light
            </Button>
            <Button variant="secondary" size="sm" onClick={() => submit("just-right")}>
              Just right
            </Button>
            <Button variant="secondary" size="sm" onClick={() => submit("too-heavy")}>
              Too heavy
            </Button>
          </div>
        )}
      </section>
    </div>
  );
}
